import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        // Technical Vitality — Neon Pulse design system
        surface: {
          DEFAULT: "#0e0e11",
          dim: "#0e0e11",
          bright: "#2c2c30",
          container: {
            DEFAULT: "#19191d",
            low: "#131316",
            high: "#1f1f23",
            highest: "#25252a",
            lowest: "#000000",
          },
          variant: "#25252a",
          tint: "#aea2ff",
        },
        neon: {
          violet: "#aea2ff",
          "violet-dim": "#7157ff",
          cyan: "#00eefc",
          "cyan-dim": "#00deec",
          pink: "#ff6b98",
          "pink-dim": "#e4006c",
        },
        "on-surface": {
          DEFAULT: "#f3f0f4",
          variant: "#acaaae",
        },
        outline: {
          DEFAULT: "#767579",
          variant: "#48474b",
        },
        // Basin & Range — Mojave Monolith design system (flat keys to avoid TW3 nesting issues)
        "br-bg": "#12110f",
        "br-surface": "#12110f",
        "br-surface-lowest": "#0c0b09",
        "br-surface-low": "#1a1815",
        "br-surface-container": "#252219",
        "br-surface-high": "#332e24",
        "br-surface-highest": "#3d3730",
        "br-surface-bright": "#4a4238",
        "br-primary": "#e5c276",
        "br-primary-container": "#c4a35a",
        "br-primary-dim": "#d4b05e",
        "br-on-primary": "#3f2e00",
        "br-secondary": "#d5c5a9",
        "br-tertiary": "#d3c4b2",
        "br-on-surface": "#e6e1e1",
        "br-on-surface-variant": "#d0c5b4",
        "br-outline": "#9a9182",
        "br-outline-variant": "#584e3e",
        // Apache Springs — Ochre & Ash design system
        "as-surface": "#161310",
        "as-surface-low": "#1e1b18",
        "as-surface-container": "#221f1c",
        "as-surface-high": "#2d2926",
        "as-primary": "#ffb688",
        "as-primary-container": "#ce7c44",
        "as-on-primary": "#512400",
        "as-secondary": "#f5bd64",
        "as-tertiary": "#d5c5a9",
        "as-on-surface": "#e9e1dc",
        "as-on-surface-variant": "#d9c2b5",
        "as-outline": "#a18d81",
        "as-outline-variant": "#54433a",
        // Canyon Expedition — Precision Brutalism design system
        "ce-surface": "#141312",
        "ce-surface-low": "#1d1b1a",
        "ce-surface-container": "#211f1e",
        "ce-surface-high": "#2b2a28",
        "ce-surface-highest": "#363433",
        "ce-surface-lowest": "#0f0e0d",
        "ce-surface-bright": "#3b3937",
        "ce-primary": "#ffb598",
        "ce-primary-container": "#f7600c",
        "ce-on-primary": "#591c00",
        "ce-on-primary-fixed": "#370e00",
        "ce-secondary": "#f5bd64",
        "ce-secondary-container": "#825901",
        "ce-on-surface": "#e6e1df",
        "ce-on-surface-variant": "#e3bfb2",
        "ce-outline": "#aa8a7e",
        "ce-outline-variant": "#5a4137",
        "ce-tertiary": "#d0c4bc",
        // Forest House — bone & red, May 2026 art-car deployment
        "fh-bg": "#0A0A0F",
        "fh-card": "#12121A",
        "fh-text": "#D4C4B0",
        "fh-accent": "#C42525",
      },
      fontFamily: {
        sans: ["var(--font-manrope)", "system-ui", "sans-serif"],
        mono: ["var(--font-geist-mono)", "monospace"],
        fh: ["var(--font-inter)", "system-ui", "sans-serif"],
      },
      keyframes: {
        fadeUp: {
          from: { opacity: "0", transform: "translateY(16px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
      },
    },
  },
  plugins: [],
};
export default config;
